units: [[10, 64, 32, 16, 3], [10, 128, 32, 16, 3], [10, 32, 16, 8, 3]]
activations: [['relu', 'relu', 'relu', 'relu'], ['relu', 'relu', 'relu', 'sigmoid'], ['relu', 'relu', 'sigmoid', 'sigmoid']]
weight_initializer: ['random_normal', 'glorot_uniform']
bias_initializer: ['random_normal', 'zeros']
learning_rate: [0.001, 0.01, 0.1, 0.5, 0.7]
# regularizer: [None, 'l1', 'l2']
# lambda: [0.01, 0.001, 0.1]
momentum: [0.01, 0.7, 0.9]
loss: ['mean_squared_error']
metrics: [['root_mean_squared_error']]
epochs: [1000, 2000]
batch_size: [8, 16, 32, 64]
