units: [
  [10, 64, 32, 3],
  [10, 128, 64, 3],
  [10, 164, 82, 3],
]
activations: [
  ['relu', 'relu', 'identity'],
  ['relu', 'tanh', 'identity'],
]
weight_initializer: ['glorot_uniform']
bias_initializer: ['zeros']
learning_rate: [0.0001, 0.0005, 0.0006, 0.0008]
momentum: [0.65, 0.7, 0.73, 0.75, 0.77]
loss: ['mean_squared_error']
metrics: [['root_mean_squared_error', 'mean_euclidean_error']]
epochs: [10000, 12000, 15000]
batch_size: [12, 14, 16]
regularizer: ['l2']
lambd: [0.0, 0.000005, 0.00001]
early_stopping: [True, False]
start_from_epoch: [5000]
patience: [40, 50]
delta: [0.0001, 0.00001]
monitor: ['mean_squared_error']
restore_best_weights: [True]
