units: [[17, 4, 1],[17, 6, 1],[17, 8, 1],[17, 10, 1],[17, 12, 1],[17, 14, 1]]
activations: [['sigmoid', 'sigmoid'], ['relu', 'sigmoid'], ['relu', 'tanh'], ['relu','relu']]
weight_initializer: ['random_normal', 'range', 'glorot_uniform']
bias_initializer: ['random_normal', 'range', 'zeros']
learning_rate: [0.005, 0.007, 0.01, 0.03, 0.05, 0.07, 0.1, 0.25, 0.5, 0.75]
regularizer: [None, 'l1', 'l2']
lambda: [0, 0.001, 0.002, 0.005 ,0.01, 0.05, 0.1, 0.25]
momentum: [0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
loss: ['mean_squared_error']
metrics: [['binary_accuracy']]
epochs: [350, 450, 550, 650]
batch_size: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 124]
