units: [[17, 4, 1], [17, 5, 1]]
activations: [['sigmoid', 'sigmoid'], ['relu', 'sigmoid']]
weight_initializer: ['random_normal', 'range', 'fan_in', 'zeros', 'glorot_uniform']
bias_initializer: ['random_normal', 'range', 'zeros']
learning_rate: [0.9, 0.7, 0.5, 0.1, 0.05, 0.01]
momentum: [0.9, 0.7, 0.5, 0.1, 0.05, 0.01]
loss: ['mean_squared_error', 'binary_cross_entropy']
metrics: [['binary_accuracy']]
epochs: [500]
batch_size: [8, 16, 32]

# early stopping parameters:
early_stopping: [False, True]
patience: [10, 20, 30]
start_from_epoch: [50, 100, 200]
es_delta: [0.0001, 0.001, 0.01]
restore_best_weights: [False, True]
