units: [[17, 3, 1], [17, 4, 1], [17, 5, 1]]
activations: [['sigmoid', 'sigmoid'], ['relu', 'sigmoid'],['identity', 'sigmoid']]
weight_initializer: ['random_normal', 'range', 'glorot_uniform']
bias_initializer: ['random_normal', 'range', 'zeros']
learning_rate: [0.05, 0.1, 0.5]
regularizer: [None, 'l1', 'l2']
lambda: [0]
momentum: [0.3, 0.5, 0.7]
loss: ['mean_euclidean_error_loss']
metrics: [['binary_accuracy']]
epochs: [350, 500, 700]
batch_size: [8, 10, 12, 14, 16]
