units: [[17, 4, 1], [17, 5, 1]]
activations: [['sigmoid', 'sigmoid'], ['relu', 'sigmoid']]
weight_initializer: ['random_normal', 'range', 'fan_in', 'zeros', 'glorot_uniform']
bias_initializer: ['random_normal', 'range', 'zeros']
learning_rate: [0.9, 0.7, 0.5, 0.1, 0.05, 0.01]
momentum: [0.9, 0.7, 0.5, 0.1, 0.05, 0.01]
loss: ['mean_squared_error', 'binary_cross_entropy']
metrics: [['binary_accuracy']]
epochs: [1000]
batch_size: [8, 16, 32]