units: [[17, 4, 2], [17, 5, 2]]
activations: [['sigmoid', 'sigmoid'], ['relu', 'sigmoid']]
initializer: ['random']
learning_rate: [0.9, 0.5, 0.1, 0.05, 0.01, 0.005, 0.001]
momentum: [0]
loss: ['mean_squared_error', 'cross_entropy']
metrics: [['accuracy']]
epochs: [500]
batch_size: [20]