units: [[17, 4, 2], [17, 5, 2]]
activations: [['sigmoid', 'sigmoid'], ['relu', 'sigmoid']]
initializer: ['random']
learning_rate: [0.9]
momentum: [0]
loss: ['MSE']
metrics: [['Accuracy']]
epochs: [500]
batch_size: [20]